name: 生成 msg 文件

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  thtk:
    name: 编译 thtk

    runs-on: windows-latest

    env:
      # 最新支持虹龙洞的版本
      THTK_REF: bff12bec68ff5395d9f5907fb0c2fd8de3d7981a

    # 参考 thtk 的 INSTALL 自述文件
    steps:
      - name: 缓存 thtk
        id: fff
        uses: actions/cache@v2
        with:
          path: build\bin
          key: windows-build-thpatch-thtk-${{ env.THTK_REF }}
      - name: 克隆 thtk
        if: steps.fff.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # 克隆 thtk repo
          repository: thpatch/thtk
          # 克隆最新支持虹龙洞的版本
          ref: ${{ env.THTK_REF }}
          # 克隆依赖项
          # submodules: 'recursive'
      # 其实是修复 thtk 的 libpng 引用
      - name: 克隆依赖项
        if: steps.fff.outputs.cache-hit != 'true'
        run: |
          git submodule set-url thanm/libpng https://github.com/glennrp/libpng.git
          git submodule update --recursive --init
      - name: 下载 CMake
        if: steps.fff.outputs.cache-hit != 'true'
        uses: lukka/get-cmake@main
      - name: 下载 WinFlexBison
        if: steps.fff.outputs.cache-hit != 'true'
        working-directory: C:/
        run: |
          curl -L -s -o winflexbison.zip https://github.com/lexxmark/winflexbison/releases/download/v2.5.24/win_flex_bison-2.5.24.zip
          mkdir winflexbison
          7z x winflexbison.zip -oC:\winflexbison -y -aoa -bb0 -bso0
          del winflexbison.zip
          echo "C:\winflexbison" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
          refreshenv
      - name: 配置项目
        if: steps.fff.outputs.cache-hit != 'true'
        run: |
          mkdir build && cd build
          mkdir bin
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\build\bin"
      - name: 编译项目
        if: steps.fff.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          cmake --build .
          cmake --install . --config Debug
      # 供之后使用
      - name: 上传 thtk
        uses: actions/upload-artifact@v2
        with:
          path: build\bin
          name: thtk

  create_all_msg:
    name: 编译 msg
    
    runs-on: windows-latest
    
    needs: [thtk] # （
    steps:
      - uses: actions/checkout@v2
        name: 克隆 汉化 repo
      - name: 下载 thtk
        uses: actions/download-artifact@v2
        with:
          name: thtk
          path: C:\thtk
      - name: 加入 PATH
        run: |
          echo "C:\thtk\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
          refreshenv
      - name: 设置提交作者
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: rebase repo
        run: |
          git pull --rebase
      - name: 编译 msg
        run: |
          ./create_all_msg.ps1
      - name: 提交
        run: |
          git commit -am "生成对话文件"
          git push
